### ISSUE TITLE
Ability to provide generator-specific hints outside schema

### ISSUE THREAD

**Issue by eirnym** [joelittlejohn/jsonschema2pojo#1109]
The generator-specific hints are good to have, but would it be possible to add an ability to provide those hints outside the generator? 
They're useful only when you generate java classes, but for other languages or projects they're redundant or they may want to name the whole class set differently for some reason.

The example is an `XJB` file contains mapping URIs to additional generator-specific hints. In case of JsonSchema2Pojo I see this file in following format, basically `json path from schema root folder -> definition`

```yaml
"my/super_object.yaml":
    javaType: BaseSchemaObject
"my/sub/type_response_common.yaml":
   existingJavaType: java.util.Map<String, TypeResponseObject>  # see below
"my/sub/type_response_common.yaml#definitions/sub_type":
   internal: true   # use internal class instead of generation
```

and so on
