### ISSUE TITLE
POJOs from YAML are not deep enough

### ISSUE THREAD

**Issue by javydreamercsw** [joelittlejohn/jsonschema2pojo#1112]
For example the following yaml section:

```
patchesJson6902:

- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: x
  patch: |
    - op: add
      path: path
      value:
        configMapRef:
          name: name
```

Ends up being 2 classes:

1. PatchesJson6902
1. Target

When I was expecting 4:
1. PatchesJson6902
1. Target
1. Patch
1. Op

I found no way to make it go deeper. The JSON version seems to go deeper.
