### ISSUE TITLE
Respect format int32/int64

### ISSUE THREAD

**Issue by jklingsporn** [joelittlejohn/jsonschema2pojo#855]
Given this yaml schema
```
type: object
properties:
  thisShouldBeInt:
    type: integer
    format: int32
  thisShouldBeLong:
    type: integer
    format: int64
```
it generates a data object with both fields being `Integer` and not - as one would suspect - `thisShouldBeLong` being of type `Long`. As a workaround, I could use format `utc-millisec` but I really think format `int64` should render `Long`too.
